# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1fbecc6adc5abb6ba6a11361a1af4c6727db25a9c55933995d60779515954feebc8e3f016ec042f1140b3bb418eba4dba04214254085749800f8f82f6676fefd

test:
  secret_key_base: 6a55106840932b66c5bf3b92e8c7674bff08063735a3a3d1b9d146add313b023285cd7cd35aa96b936282834333ed1e8284fc4ae30293d735f94542a2b3509a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
